add apt-get module

diff --git a/modules/apt-get b/modules/apt-get
--- a/modules/apt-get
+++ b/modules/apt-get
@@ -121,17 +121,17 @@ ag:testppa() {
   fi
 
   # validate source list directory
-  dirname "$src_list"
-  list_dir=$?
-  if [[ ! -d "$list_dir" ]]; then
-    echo "invalid source list directory: $list_dir"
-    return 1
-  fi
+  #dirname "$src_list"
+  #list_dir=$?
+  #if [[ ! -d "$list_dir" ]]; then
+  #  echo "invalid source list directory: $list_dir"
+  #  return 1
+  #fi
 
   # if the list does not exist, no need to test for ppa
   if [[ ! -f "$src_list" ]]; then
     # the file does not exist yet
-    return 0
+    return 1
   fi
 
   # attempt to match the ppa within the list file
